### ISSUE TITLE
Touch scroll doesn't work on Microsoft Edge

### ISSUE THREAD

**Issue by filfat** [noraesae/perfect-scrollbar#374]
Hi, it seems like the plugin doesn't work on Microsoft Edge. A fix for this would be super. :)

Thanks.

**Comment by behz** [comment]
I faced same problem. I have three windows laptops. all updated to windows 10.  Perfect Scrollbar works perfect on IE 11 on all of them, but on two of them which are lenovo thinkpad it doesn't work on Edge browser when scrolling with trackpad. mouse wheel scrolls but there is no scroll UI.

**Comment by filfat** [comment]
Enabling "MSPointer event interface" inside about:flags fixes the issue, but that isn't really consumer friendly.

**Comment by JoshChoice** [comment]
Facing this issue too. Any more leads...?

**Comment by MattyBalaam** [comment]
In src/js/lib/helper.js I can see that a test for msMaxTouchPoints is used to look for pointer events. My hunch is that Edge no longer vendor prefixes this and that the test should be for maxTouchPoints first, and then msMaxTouchPoints for legacy browsers. At the moment I do not have a touch-enabled Windows 10 machine so can not test fully, but try this line instead:

supportsIePointer: window.navigator.maxTouchPoints !== null || window.navigator.msMaxTouchPoints !== null

There may be some other references to ms prefixed pointer events elswhere in the code which might need changing, but it may be as simple as changing that line.

**Comment by behz** [comment]
@MattyBalaam thanks. I just tried that line didn't fix it. 

I found a clue, I put alert(e.pointerType) inside  src/js/plugin/handler/touch.js > function touchStart(e) {...}
when I scroll with either mouse or trackpad on IE 11 and Edge(on pc that PS works),  e.pointerType returns "mouse". but using trackpad on affected machine returns "touch"

I'm also suspicious of MSPOINTER_TYPE_MOUSE as it's not supported on edge
http://compatibility.shwups-cms.ch/en/home?&property=MSPointerEvent.MSPOINTER_TYPE_MOUSE

**Comment by MattyBalaam** [comment]
I'm not 100% sure about the logic on that test, but try changing the line to:

`if (e.pointerType && e.pointerType !== 'mouse' && e.pointerType !== e.POINTER_TYPE_MOUSE && e.pointerType !== e.MSPOINTER_TYPE_MOUSE) {

**Comment by MattyBalaam** [comment]
something else I have noticed. The CSS only has 

 -ms-touch-action: none;

but 

touch-action: none

will also need to be added after this

**Comment by behz** [comment]
Good find @MattyBalaam  touch-action: none fix the scrolling problem. thx

Though it fixes scrolling but the fact that using trackpad triggers touch functions instead mouse, makes some problems. there is no easing effect and touchmove moves page a little(much little compared to IE11).

**Comment by themevan** [comment]
Same issue here. I tried to use touch-action:none to fix the scrolling problem on Win8 touch screen, but the mouse can't scroll the page any more...  Any solution?

**Comment by elantion** [comment]
It's not just make Perfect-scrollbar work. It's also making Iscroll work in Edge. Interesting, what's the magic of this css property?

**Comment by noraesae** [comment]
#401 may help the problem? Can anybody try the PR?

**Comment by iver56** [comment]
@noraesae I tried that PR. Indeed, it fixes touch scrolling in Microsoft Edge.

**Comment by noraesae** [comment]
Thanks to several reviews, I've just merged #401. Please feel free to open an issue when a similar problem's happening.

**Comment by iver56** [comment]
@noraesae Perfect! That's worth a release, isn't it? :)

**Comment by noraesae** [comment]
@iver56 Absolutely. Will do now!

**Comment by Samir-ouchene** [comment]
I had the same problem, I downloaded the new driver from the synaptic website ... but It still not working, but when I uncheck "Three-Finger Flick" it works fine, Now I can scroll inside MS Edge, settings ....etc
